name: 'Detect Terraform Changes'
description: 'Initializes and plans Terraform changes'
runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.12.0"

    - name: Terraform Init
      shell: bash
      run: terraform init

    - name: Terraform Plan
      shell: bash
      run: terraform plan -input=false