name: Detect Terraform Changes
on:
  push:
    branches:
      - main

permissions:
  id-token: write   # Required for requesting the JWT for OIDC
  contents: read    # Required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume:  ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: us-east-1

      - name: Detect Terraform Changes
        run: |
          aws s3 sync ./build s3://my-example-bucket --delete
