name: PR Security & Plan Scan
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

concurrency:
  group: tf-state-lock-main
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  pull-requests: write  # Added to allow posting the plan as a comment

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: us-east-1

      - name: Run Terraform Scan
        id: tf_logic
        uses: ./.github/actions/detect_terraform_changes
        with:
          path: 'aws/payer'

      - name: Post Plan to PR
        uses: mshick/add-pr-comment@v2
        if: github.event_name == 'pull_request'
        with:
          message: |
            #### Terraform Plan for `aws/payer` 📖
            ```terraform
            ${{ steps.tf_logic.outputs.plan_output }}
            ```