name: PR Security & Plan Scan
on:
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: us-east-1

      - name: Run Terraform Logic
        uses: ./.github/actions/detect_terraform_changes